// frontend/src/pages/ImportProject/ImportProjectPage.jsx
import React, { useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowLeft, Upload, FileJson, Terminal, CheckCircle, X } from 'lucide-react';
import Button from '@/components/ui/Button';
import { ROUTES } from '@/constants/routes';
import { supabase } from '@/lib/supabase';
import toast from 'react-hot-toast';
import { pageTransition } from '@/constants/motion';

export default function ImportProjectPage() {
  const navigate = useNavigate();
  const fileInputRef = useRef(null);
  const [dragOver, setDragOver] = useState(false);
  const [file, setFile] = useState(null);
  const [importing, setImporting] = useState(false);
  const [parseError, setParseError] = useState(null);

  const handleFile = (f) => {
    if (!f) return;
    if (!f.name.endsWith('.json')) {
      setParseError('Only .json files are supported.');
      return;
    }
    setFile(f);
    setParseError(null);
  };

  const handleDrop = (e) => {
    e.preventDefault();
    setDragOver(false);
    handleFile(e.dataTransfer.files[0]);
  };

  const handleImport = async () => {
    if (!file) return;
    setImporting(true);
    setParseError(null);

    try {
      const text = await file.text();
      let json;
      try {
        json = JSON.parse(text);
      } catch {
        throw new Error('Invalid JSON — the file could not be parsed.');
      }

      // Accept either a single project object or a roadmap export
      const title = json.metadata?.title || json.title || file.name.replace('.json', '');
      const content = JSON.stringify(json);

      const { data: { session } } = await supabase.auth.getSession();
      if (!session) {
        toast.error('You must be signed in to import a project.');
        navigate(ROUTES.AUTH);
        return;
      }

      const { data, error } = await supabase
        .from('roadmap')
        .insert({
          user_id: session.user.id,
          title,
          content,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        })
        .select('id')
        .single();

      if (error || !data) throw new Error(error?.message ?? 'Import failed');

      toast.success('Project imported successfully.');
      navigate(`/project/${data.id}`);
    } catch (err) {
      setParseError(err.message || 'Import failed. Please check the file and try again.');
    } finally {
      setImporting(false);
    }
  };

  return (
    <motion.div {...pageTransition} className="mx-auto max-w-2xl px-4 py-10 sm:px-6">
      <button
        onClick={() => navigate(ROUTES.DASHBOARD)}
        className="mb-6 flex items-center gap-1.5 text-sm text-[var(--text-muted)] hover:text-[var(--text-primary)] transition-colors"
      >
        <ArrowLeft size={14} /> Back to dashboard
      </button>

      <h1 className="mb-2 text-2xl font-bold text-[var(--text-primary)]">Add a project</h1>
      <p className="mb-8 text-sm text-[var(--text-secondary)]">
        Import a plan generated by Claude Code, or connect your MCP server to sync automatically.
      </p>

      {/* Option 1 — MCP sync (primary) */}
      <div className="mb-6 rounded-2xl border border-[var(--border)] bg-[var(--bg-surface)] p-6">
        <div className="mb-4 flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[var(--accent-subtle)]">
            <Terminal size={20} style={{ color: 'var(--accent)' }} />
          </div>
          <div>
            <h2 className="font-semibold text-[var(--text-primary)]">Connect Claude Code (recommended)</h2>
            <p className="text-xs text-[var(--text-secondary)]">Generate a plan from your actual codebase — syncs automatically</p>
          </div>
        </div>
        <ol className="space-y-2 text-sm text-[var(--text-secondary)]">
          <li className="flex items-start gap-2">
            <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[var(--accent-subtle)] text-xs font-bold" style={{ color: 'var(--accent)' }}>1</span>
            Get your MCP token from <button onClick={() => navigate(ROUTES.SETTINGS)} className="underline hover:text-[var(--text-primary)]">Settings → Claude Code Integration</button>
          </li>
          <li className="flex items-start gap-2">
            <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[var(--accent-subtle)] text-xs font-bold" style={{ color: 'var(--accent)' }}>2</span>
            In your project terminal: <code className="rounded bg-[var(--bg-elevated)] px-1.5 py-0.5 font-mono text-xs">npx @proplan/mcp@latest init</code>
          </li>
          <li className="flex items-start gap-2">
            <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[var(--accent-subtle)] text-xs font-bold" style={{ color: 'var(--accent)' }}>3</span>
            Choose cloud mode, paste your token. Open Claude Code — your projects sync automatically.
          </li>
        </ol>
      </div>

      {/* Option 2 — File import */}
      <div className="rounded-2xl border border-[var(--border)] bg-[var(--bg-surface)] p-6">
        <div className="mb-4 flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[var(--bg-elevated)]">
            <FileJson size={20} className="text-[var(--text-secondary)]" />
          </div>
          <div>
            <h2 className="font-semibold text-[var(--text-primary)]">Import from file</h2>
            <p className="text-xs text-[var(--text-secondary)]">Upload a project JSON exported from Claude Code</p>
          </div>
        </div>

        <motion.label
          htmlFor="import-file"
          whileHover={{ scale: 1.01 }}
          className={`flex cursor-pointer flex-col items-center gap-2 rounded-xl border-2 border-dashed px-4 py-8 transition-colors ${
            dragOver ? 'border-[var(--accent)] bg-[var(--accent-subtle)]' : 'border-[var(--border)] hover:border-[var(--accent)]'
          }`}
          onDragOver={e => { e.preventDefault(); setDragOver(true); }}
          onDragLeave={() => setDragOver(false)}
          onDrop={handleDrop}
        >
          {file ? (
            <div className="flex items-center gap-2">
              <CheckCircle size={16} className="text-green-500" />
              <span className="text-sm font-medium text-[var(--text-primary)]">{file.name}</span>
              <button
                type="button"
                onClick={e => { e.preventDefault(); setFile(null); setParseError(null); }}
                className="text-[var(--text-muted)] hover:text-[var(--destructive)]"
              >
                <X size={14} />
              </button>
            </div>
          ) : (
            <>
              <Upload size={20} className="text-[var(--text-muted)]" />
              <span className="text-sm text-[var(--text-muted)]">Drop a .json file or click to browse</span>
            </>
          )}
          <input
            id="import-file"
            ref={fileInputRef}
            type="file"
            accept=".json"
            className="hidden"
            onChange={e => handleFile(e.target.files[0])}
          />
        </motion.label>

        {parseError && (
          <p className="mt-2 text-sm text-[var(--destructive)]">{parseError}</p>
        )}

        {file && !parseError && (
          <div className="mt-4 flex justify-end">
            <Button onClick={handleImport} loading={importing} disabled={!file}>
              {importing ? 'Importing…' : 'Import Project'}
            </Button>
          </div>
        )}
      </div>
    </motion.div>
  );
}
