import React from 'react';
import { Link } from 'react-router-dom';
import { 
  ArrowRight, 
  Target, 
  Users, 
  TrendingUp, 
  Zap,
  CheckCircle,
  Star
} from 'lucide-react';
import Logo from '../../components/Logo/Logo';
import vincentImage from '../../assets/images/testimonials/vincent.jpg';
import sudeepImage from '../../assets/images/testimonials/sudeep.jpg';
import prosperImage from '../../assets/images/testimonials/prosper.jpg';
import './Home.css';

function Home() {
  const features = [
    {
      icon: Zap,
      title: 'AI-Powered Planning',
      description: 'Get personalized project roadmaps generated by advanced AI based on your skills and goals.'
    },
    {
      icon: Target,
      title: 'Smart Milestones',
      description: 'Break down complex projects into manageable tasks with intelligent milestone tracking.'
    },
    {
      icon: TrendingUp,
      title: 'Progress Analytics',
      description: 'Visualize your progress with beautiful charts and stay motivated throughout your journey.'
    },
    {
      icon: Star,
      title: 'Custom Templates',
      description: 'Save and reuse your successful project structures with customizable templates.'
    }
  ];

  const testimonials = [
    {
      name: 'Vincent Anim-Addo',
      role: 'Meta U Intern',
      content: 'This is exactly what I need for my personal and classroom projects. Having a platform that helps break down my ideas into manageable steps while providing easy access to relevant resources would be a game-changer.',
      avatar: vincentImage
    },
    {
      name: 'Sudeep Joshi',
      role: 'Amazon SWE Intern',
      content: 'If I had a platform like ProPlan, I believe I would have accomplished more by now. The structured approach to project planning and resource management is exactly what developers need.',
      avatar: sudeepImage
    },
    {
      name: 'Prosper Banda',
      role: 'Software Engineer at Meta',
      content: 'Applications like ProPlan keeps you on track and helps you navigate and accomplish your goals on time. I believe I will enjoy using this platform.',
      avatar: prosperImage
    }
  ];

  return (
    <div className="landing">
      <section className="hero">
        <div className="hero-overlay"></div>
        <div className="hero-content">
          <div className="hero-inner">
            <div className="logo-container">
              <Logo size="lg" className="logo" />
            </div>
            
            <h1 className="hero-title">
              <span className="gradient-text">
                Project Planning
              </span>
            </h1>
            
            <p className="hero-subtitle">
              Break down complex goals into actionable steps
            </p>
            
            <div className="hero-buttons">
              <Link to="/register" className="btn-primary">
                Get Started Free
                <ArrowRight className="btn-icon" />
              </Link>
              <Link to="/login" className="btn-secondary">
                Sign In
              </Link>
            </div>
          </div>
        </div>
        <div className="hero-fade"></div>
      </section>

      <section className="features">
        <div className="features-overlay"></div>
        <div className="features-content">
          <div className="features-header">
            <h2 className="section-title">
              Why Choose <span className="gradient-text">ProPlan</span>?
            </h2>
            <p className="section-subtitle">
              Transform the way you plan and execute projects
            </p>
          </div>

          <div className="features-grid">
            {features.map((feature) => (
              <div
                key={feature.title}
                className="feature-card"
              >
                <div className="feature-icon">
                  <feature.icon />
                </div>
                <h3 className="feature-title">
                  {feature.title}
                </h3>
                <p className="feature-description">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
        <div className="features-fade"></div>
      </section>

      <section className="testimonials">
        <div className="testimonials-overlay"></div>
        <div className="testimonials-content">
          <div className="testimonials-header">
            <h2 className="section-title">
              Loved by <span className="gradient-text">Students & Developers</span>
            </h2>
          </div>

          <div className="testimonials-grid">
            {testimonials.map((testimonial) => (
              <div
                key={testimonial.name}
                className="testimonial-card"
              >
                <div className="testimonial-header">
                  <img
                    src={testimonial.avatar}
                    alt={testimonial.name}
                    className="testimonial-avatar"
                  />
                  <div className="testimonial-info">
                    <h4 className="testimonial-name">
                      {testimonial.name}
                    </h4>
                    <p className="testimonial-role">
                      {testimonial.role}
                    </p>
                  </div>
                </div>
                <p className="testimonial-content">
                  {testimonial.content}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <footer className="footer">
        <div className="footer-content">
          <div className="footer-grid">
            <div className="footer-brand">
              <div className="footer-logo">
                <Logo size="sm" className="logo-sm" />
                <span className="footer-logo-text">ProPlan</span>
              </div>
              <p className="footer-tagline">
                We help you plan your projects and achieve your goals
              </p>
            </div>
            
            <div className="footer-links">
              <h3 className="footer-title">Quick Links</h3>
              <ul>
                <li>
                  <Link to="/features">Features</Link>
                </li>
                <li>
                  <Link to="/about">About Us</Link>
                </li>
              </ul>
            </div>

            <div className="footer-links">
              <ul>
                <li>
                  <Link to="/terms">Terms of Service</Link>
                </li>
                <li>
                  <Link to="/contact">Contact</Link>
                </li>
              </ul>
            </div>
          </div>

          <div className="footer-bottom">
            <p className="footer-copyright">
              © {new Date().getFullYear()} ProPlan. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}

export default Home; 